### ISSUE TITLE
Apakah sama atau berbeda fungsi atara xhr dan run?

### ISSUE THREAD

**Issue by BerkasKita** [siwaluh/BloggerScript#1]
const bloggerFeed = new BloggerScript();

bloggerFeed.xhr('https://blog_url.blogspot.com/feeds/posts/default?alt=json-in-script&max-results=20', function(entry) {
  console.log(entry); //Output Array entry
});
> 
dan
> 
const bloggerSitemap = new BloggerSitemap();

bloggerSitemap.run('https://blog_url.blogspot.com/feeds/posts/default', function(entry) {
  console.log(entry); //Output Array Entry
});

**Comment by siwaluh** [comment]
Untuk hasil akhir nya sama saja berupa daftar postingan, yang berbeda isi nya.

Untuk fungsi `run` hanya berlaku untuk `BloggerSitemap`, `BloggerRandom` dan `BloggerRelated` saja, tidak untuk `BloggerScript`.

1. BloggerSitemap
Mengambil Semua Postingan.

2. BloggerRandom
Mengambil Postingan secara acak

3. BloggerRelated
Mengambil Postingan dari berbagai category dan di satukan.

**Comment by BerkasKita** [comment]
Terimakasih atas jawabanya. saya baru  menyadari ternyata ada **BloggerSitemap**, **BloggerRandom**, **BloggerRelated** dan **BloggerScript**.
