### ISSUE TITLE
Apakah BloggerScript bisa untuk feed komen?

### ISSUE THREAD

**Issue by BerkasKita** [siwaluh/BloggerScript#3]

**Comment by siwaluh** [comment]
ya, baru saja di update.
[Contoh Source Code](https://github.com/siwaluh/BloggerScript/tree/main/source_code/recent_coments).

## Cara Menggunakan
```
let feedComments = new BloggerComments({
  'noImage': 'url_noImage',
  'sizeImage': 'w40-h40-c-rw',
  'mainUrl': '' https://emissionhex.blogspot.com
});

//execute Code
feedComments.run(postId, jumlahPostingan, callback, xhrType);
```

### Mengambil comments 
Bagian `postId` di kasih value `false`, jika ingin mengambil semua postingan.
Dan untuk mengambil comments dari postingan tertentu `postId` di isi dengan id postingan tersebut contoh: `'977954213605698544'`
```
feedComments.run(false, 10, function(entry) {
  console.log(entry); //Output List Komentar
}, false);
```
Untuk bagian `xhrType` di kasih false karena url blog yang menampilkan recent comments nya berbeda.
Misal Blog1 menampilkan recent comments dari Blog2, adapun jika Blog1 menampilkan recent comments dari Blog1 juga maka  bagian `xhrType`  bisa di kosongkan.
```
feedComments.run(false, 10, function(entry) {
  console.log(entry); //Output List Komentar
});
```

### Output Array Entry
Output nya sama saja dengan mengambil postingan.

**Comment by BerkasKita** [comment]
ohh nya makasih atas updatenya.
