### ISSUE TITLE
Sitemap Pagination Bug

### ISSUE THREAD

**Issue by wernayasa** [siwaluh/BloggerScript#5]
Mau lapor bug Sitemap Pagination tidak bisa mengambil lebih dari 148 post.
Ini url nya: www.novelturk.com

**Comment by siwaluh** [comment]
fixed.
[Demo](https://siwaluh.github.io/BloggerScript/source_code/sitemap_pagination/cek_1000/)
[Code](https://github.com/siwaluh/BloggerScript/tree/main/source_code/sitemap_pagination/cek_1000)

**Comment by wernayasa** [comment]
ok, mantap

**Comment by wernayasa** [comment]
Maaf, bugnya aku buka lagi.
Untuk situs: 
www.kivanime.my.id
hexanime-bt.blogspot.com

Post Series tidak muncul.
Berikut confignya:
`{firstContent:!0,host:"www.kivanime.my.id",label:"Series"}`

**Comment by siwaluh** [comment]
fix

**Comment by wernayasa** [comment]
Makasih.
